### ISSUE TITLE
Need a 2016 update to the news

### ISSUE THREAD

**Issue by rejon** [freebassel/freebassel.org#100]
Now FOUR MONTHS since our friend has been missing.

The tweet dana made in english and arabic can be copied and used: 

* https://twitter.com/freebassel/status/694628290666053632
* https://twitter.com/freebassel/status/694629025088716800

**Comment by christopheradams** [comment]
Updated in dac3a6db5fb190fcd0c98ce2fa1cabd222c4ecaa
