### ISSUE TITLE
add jimmy wales quote

### ISSUE THREAD

**Issue by rejon** [freebassel/freebassel.org#102]
from that ccn piece

**Comment by christopheradams** [comment]
> Syria has one of the lowest scores for Internet freedom in the world, ranking above only China and Iran.
> It was under these circumstances that Bassel Khartabil, a free culture advocate, open software developer and Wikipedian, had the courage to dream of a different reality.

>  He distinguished himself on the global stage as a passionate advocate for free knowledge in the Arab world, pushing for greater inclusion, translation and exchange of ideas.

**Comment by christopheradams** [comment]
Done 3a973efe78f9ec64adeaa80b4c152c444b1dfc80
