### ISSUE TITLE
add eff danny o brien quote

### ISSUE THREAD

**Issue by rejon** [freebassel/freebassel.org#103]

**Comment by christopheradams** [comment]
https://www.eff.org/deeplinks/2015/10/fears-grow-safety-imprisoned-syrian-open-source-developer-bassel-khartabil

https://www.eff.org/deeplinks/2015/09/taken-offline-years-prison-love-technology

not sure if there's a usable quote in there?

> Bassel's not online right now, despite being an enthusiastic adopter of new technology when it reached his home town of Damascus. Bassel's not online, because he was arrested and thrown in jail for his love of the Internet and free culture

**Comment by rejon** [comment]
I will email danny for a new one. If you have more high level quotes like
obama, file em and task me.
