### ISSUE TITLE
add john kerry us state dept. quote

### ISSUE THREAD

**Issue by rejon** [freebassel/freebassel.org#104]

**Comment by christopheradams** [comment]
> These freedoms and the Universal Declaration in which they are now enshrined serve as a beacon for Tunisians as they continue their brave transition from dictatorship to democracy; for Burmese who fought tirelessly to bring about this year’s historic election; for former member of parliament and human rights activist Murod Juraev of Uzbekistan released at long last; for prisoners of conscience who still long for their freedom, such as Liu Xiaobo of China, Bassel Khartabil of Syria, Leopoldo Lopez of Venezuela; and journalists, artists, religious minority leaders, and women’s rights activists detained unjustly in Iran.

Important part:

> These freedoms [_of speech and religion, from want and fear_] and the Universal Declaration in which they are now enshrined serve as a beacon... for prisoners of conscience who still long for their freedom, such as Liu Xiaobo of China, Bassel Khartabil of Syria, Leopoldo Lopez of Venezuela"

**Comment by christopheradams** [comment]
maybe drop the other names

**Comment by christopheradams** [comment]
http://freebassel.org/campaign/quotes/#john-kerry
