### ISSUE TITLE
add ethan zuckerman quote from media lab statements

### ISSUE THREAD

**Issue by rejon** [freebassel/freebassel.org#105]

**Comment by christopheradams** [comment]
>  Bassel worked to connect Syria with the rest of the world, and to ensure that all Syrians... could make their voices heard online.

> Bassel’s work is in the best spirit of Civic Media, working to connect contemporary Syrians to global conversations while preserving Syria’s rich history and culture.

**Comment by rejon** [comment]
Great and should let him know when live so he tweets it. Actually all
should be notified publicly on twitter when live ao they retweet and we get
more signers.

**Comment by christopheradams** [comment]
New one:

> Bassel's life and work represent the open source movement at its most generous and creative. Ending his imprisonment should be a priority for anyone concerned about openness, collaboration and intellectual freedom.

**Comment by christopheradams** [comment]
http://freebassel.org/campaign/quotes/#ethan-zuckerman
