### ISSUE TITLE
add ryan merkley cc ceo quote

### ISSUE THREAD

**Issue by rejon** [freebassel/freebassel.org#106]
from releases and blog posts

**Comment by christopheradams** [comment]
pick one

**Comment by rejon** [comment]
Task me. I will ask for a new one.

**Comment by christopheradams** [comment]
Fallback if there's not a new one:

> We... honor Bassel and his contributions to Creative Commons. And we stand with our peers in the free software and free culture communities in demanding that he be freed.

**Comment by christopheradams** [comment]
Or from the CC board:

> Mr. Khartabil’s contributions to Creative Commons have always inspired collaboration, community, and the sharing of culture and knowledge, including his leadership in the development of the #NewPalmyra, and his activism and involvement in the CC community and open internet community is deeply missed since his arrest and imprisonment without trial or assistance of counsel in March 2012.

**Comment by rejon** [comment]
Go ahead and use that as from Creative Commons.

Ryan's can be used to I'm sure

On Wed, Feb 10, 2016 at 1:29 PM, Christopher Adams <notifications@github.com

**Comment by christopheradams** [comment]
good idea

**Comment by christopheradams** [comment]
Done 3a973efe78f9ec64adeaa80b4c152c444b1dfc80
