### ISSUE TITLE
Order of quote and then person is awkward

### ISSUE THREAD

**Issue by rejon** [freebassel/freebassel.org#108]
Strange to read a quote without the intro of who is bejng quoted...also not as powerful because quote people will want to read after knowing the famous person who said it.

Also of you read down the quotes, reads like quotes are attributed to the wrong people.

**Comment by christopheradams** [comment]
Aren't most quotes followed by the attribution?

I increased the size of the speech bubble indicator connected to each pic in 88e8b27. Let me know if that helps disambiguate the quote attribution.

**Comment by rejon** [comment]
looks good
