### ISSUE TITLE
change site header text and branding to #happybdaybassel

### ISSUE THREAD

**Issue by rejon** [freebassel/freebassel.org#110]
Want to pivot on the #WhereIsBassel tag now, think people get it. If we can change to #happybdaybassel good for a couple of days, then switch back to simply #FREEBASSEL, with the current look and feel of whereisbassel is fine. Time to simplify things...get back to basics.

**Comment by christopheradams** [comment]
Ok, updated.

I made the big hashtag in the header configurable. Just edit [_config.yml](https://github.com/freebassel/freebassel.org/blob/gh-pages/_config.yml#L2) and change:

```
hashtag: "#happybdaybassel"
```
