### ISSUE TITLE
Add repo topics

### ISSUE THREAD

**Issue by mlinksva** [freebassel/freebassel.org#121]
Someone who can, consider doing. If you're such a person, you'll see an "Add Topics" link near the top of <https://github.com/freebassel/freebassel.org>. I added a few to some related repos that I have access to, see https://github.com/search?q=topic%3Afreebassel

See https://github.com/blog/2309-introducing-topics for background.

**Comment by christopheradams** [comment]
Great suggestion

**Comment by spanther** [comment]
great tweeted

https://twitter.com/freebassel/status/841626003218788352

if you guys have more fuel for updates, please update nearly #freebassel5years
