### ISSUE TITLE
catch up the news

### ISSUE THREAD

**Issue by rejon** [freebassel/freebassel.org#125]

**Comment by christopheradams** [comment]
Latest in a541c63. Please add any new links here or commit them directly.

**Comment by christopheradams** [comment]
- [ ] http://jimmywalesfoundation.org/horrific-reports-that-bassel-khartabil-has-been-executed-in-syria/

**Comment by christopheradams** [comment]
http://www.aljazeera.com/news/2017/08/bassel-khartabil-missing-syrian-palestinian-executed-170802100920059.html

**Comment by christopheradams** [comment]
https://www.alarabiya.net/mob/alarabiya-today/2017/08/02/عندما-صمتت-سوريا-بإعدام-النظام-لباسل-الصفدي.html

**Comment by christopheradams** [comment]
http://www.standard.co.uk/news/world/man-who-created-3d-version-of-palmyra-before-it-was-destroyed-by-isis-killed-by-assad-regime-a3603436.html

http://www.bostonglobe.com/metro/2017/08/03/mit-media-lab-mourns-after-reported-execution-syrian-activist/imOhwSEDbZBNZkbJBVrOFO/story.html?event=event25
