### ISSUE TITLE
Keep news up to date

### ISSUE THREAD

**Issue by christopheradams** [freebassel/freebassel.org#92]
This issue will keep track of news articles that should be posted to the site.
- [x] [MIT Researcher Bassel Khartabil Reportedly Sentenced to Death in Syria](http://www.bostonmagazine.com/news/blog/2015/12/14/bassel-khartabil-syria-mit/)
- [x] [Bassel Khartabil: fears for man who brought open internet to the Arab world](http://www.theguardian.com/technology/2015/dec/11/bassel-khartabil-fears-for-man-who-brought-open-internet-to-the-arab-world)
- [x] [MIT Researcher Reportedly Sentenced to Death in Syria](http://www.huffingtonpost.com/joichi-ito/mit-researcher-sentenced-_b_8760354.html)
- [x] [International Human Rights Day 2015](http://www.state.gov/secretary/remarks/2015/12/250541.htm)
- [x] [#FreeBassel: Death Sentence Rumored for Syrian Web Developer ](https://globalvoices.org/2015/11/13/freebassel-death-sentence-rumored-for-syrian-web-developer/)
- [x] [Публикация статьи о стороннике Creative Commons Басселе Хартабиле из Сирии, попавшем в тюрьму](http://www.creativecommons.ru/news/2015/11/16/bassel-khartabil)
- [x] [IGF 2015 Flyer on Bassel Khartabil](https://www.eff.org/document/igf-2015-flyer-bassel-khartabil)
- [x] [Syrie : Où Bassel Khartabil est-il secrètement emprisonné?](http://acatcanada.org/2015/11/01/bassel-khartabil/)
- [x] [With ISIS And A Refugee Crisis, 'Disappeared' Syrians Are Being Forgotten ](https://www.youtube.com/watch?v=i6KYOTiG3C4)
- [x] [MITメディアラボが収監中のシリア人活動家に市民メディアセンターの研究職をオファー](http://joi.ito.com/jp/archives/2015/10/26/005574.html)
- [x] [WIRED article highlights #NEWPALMYRA project launch](http://creativecommons.org/weblog/entry/46302)
- [x] [Salviamo la vita a Bassel Khartabil](http://www.tusciaweb.eu/2015/10/salviamo-vita-bassel-khartabil/)
- [x] [~~Read the story of Bassel Khartabil, Syrian prisoner who lives and risks dying for a free Internet~~](https://creativecommons.org/weblog/entry/46265)
- [x] [~~Tahotra Momba Ilay Siriana Injeniera Informatika Voafonja, Nafindra Ho Aminà Toerana Tsy Fantatra~~ ](https://mg.globalvoices.org/2015/10/05/75255/)
- [x] [~~#FREEBASSEL: Desapareix a Síria el defensor de la cultura lliure que va reconstuir Palmira en 3D~~](http://blog.wikimedia.org/ca/2015/10/13/freebassel-desapareix-a-siria-el-defensor-de-la-cultura-lliure-que-va-reconstuir-palmira-en-3d/)
- [x] [~~#FREEBASSEL: uwolnić zaginionego w Syrii aktywistę wolnej kultury~~](http://blog.wikimedia.org/pl/2015/10/13/freebassel-uwolnic-zaginionego-w-syrii-aktywiste-wolnej-kultury/)
- [x] [~~#FREEBASSEL: El defensor de la cultura libre que construyó representaciones en 3D de Palmira desapareció en Siria~~](http://blog.wikimedia.org/es/2015/10/10/freebassel-el-defensor-de-la-cultura-libre-que-construyo-representaciones-en-3d-de-palmira-desaparecio-en-siria/)
- [x] [~~#FREEBASSEL: У Сирії зник популяризатор вільної культури, який створював 3D-представлення Пальміри~~ (already posted on 2015-10-08 on wikimediaukraine.wordpress.com)](http://blog.wikimedia.org/uk/2015/10/12/freebassel-%D1%83-%D1%81%D0%B8%D1%80%D1%96%D1%97-%D0%B7%D0%BD%D0%B8%D0%BA-%D0%BF%D0%BE%D0%BF%D1%83%D0%BB%D1%8F%D1%80%D0%B8%D0%B7%D0%B0%D1%82%D0%BE%D1%80-%D0%B2%D1%96%D0%BB%D1%8C%D0%BD%D0%BE%D1%97/)
- [x] [~~http://www.architectmagazine.com/technology/an-open-source-project-to-rebuild-palmyra_o~~](http://www.architectmagazine.com/technology/an-open-source-project-to-rebuild-palmyra_o)
- [x] [~~Bassel Khartabil, prisionero sirio que vive y puede morir por un Internet Libre~~](https://medium.com/@technollama/bassel-khartabil-prisionero-sirio-que-vive-y-puede-morir-por-un-internet-libre-4a23e50e5f55?source=tw-2a62598e8fa8-1445622529408)

## Other

- [ ] [Index on Censorship](https://www.indexoncensorship.org/2015/10/syria-disclose-whereabouts-of-detained-freedom-of-expression-advocate/) - this website is not loading for me

**Comment by christopheradams** [comment]
- [ ] [Read the story of Bassel Khartabil, Syrian prisoner who lives and risks dying for a free Internet](https://creativecommons.org/weblog/entry/46265)
- [ ] [Tahotra Momba Ilay Siriana Injeniera Informatika Voafonja, Nafindra Ho Aminà Toerana Tsy Fantatra ](https://mg.globalvoices.org/2015/10/05/75255/)
- [ ] [#FREEBASSEL: Desapareix a Síria el defensor de la cultura lliure que va reconstuir Palmira en 3D](http://blog.wikimedia.org/ca/2015/10/13/freebassel-desapareix-a-siria-el-defensor-de-la-cultura-lliure-que-va-reconstuir-palmira-en-3d/)
- [ ] [#FREEBASSEL: uwolnić zaginionego w Syrii aktywistę wolnej kultury](http://blog.wikimedia.org/pl/2015/10/13/freebassel-uwolnic-zaginionego-w-syrii-aktywiste-wolnej-kultury/)
- [ ] [#FREEBASSEL: El defensor de la cultura libre que construyó representaciones en 3D de Palmira desapareció en Siria](http://blog.wikimedia.org/es/2015/10/10/freebassel-el-defensor-de-la-cultura-libre-que-construyo-representaciones-en-3d-de-palmira-desaparecio-en-siria/)
- [ ] [#FREEBASSEL: У Сирії зник популяризатор вільної культури, який створював 3D-представлення Пальміри](http://blog.wikimedia.org/uk/2015/10/12/freebassel-%D1%83-%D1%81%D0%B8%D1%80%D1%96%D1%97-%D0%B7%D0%BD%D0%B8%D0%BA-%D0%BF%D0%BE%D0%BF%D1%83%D0%BB%D1%8F%D1%80%D0%B8%D0%B7%D0%B0%D1%82%D0%BE%D1%80-%D0%B2%D1%96%D0%BB%D1%8C%D0%BD%D0%BE%D1%97/)

**Comment by christopheradams** [comment]
http://www.architectmagazine.com/technology/an-open-source-project-to-rebuild-palmyra_o

**Comment by christopheradams** [comment]
http://joi.ito.com/jp/archives/2015/10/26/005574.html

**Comment by christopheradams** [comment]
http://acatcanada.org/2015/11/01/bassel-khartabil/

**Comment by rejon** [comment]
The index on censorship is loading again: https://www.indexoncensorship.org/2015/10/syria-disclose-whereabouts-of-detained-freedom-of-expression-advocate/

**Comment by rejon** [comment]
I think most of these are updated. Closing.
